export const STORE_INITIAL_USER = 'STORE_INITIAL_USER';
export const REMOVE_INITIAL_USER = 'REMOVE_INITIAL_USER';

export const STORE_TOKEN = 'STORE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
