export const STORE_INITIAL_USER = 'STORE_INITIAL_USER';
export const STORE_AUTH_TOKEN = 'STORE_AUTH_TOKEN';
export const RESET_AUTH = 'RESET_AUTH';

export const SET_LOADER = 'SET_LOADER';
export const UNSET_LOADER = 'UNSET_LOADER';

export const SET_STATE_PREFERENCE = 'SET_STATE_PREFERENCE';
export const SET_DISTRICT_PREFERENCE = 'SET_DISTRICT_PREFERENCE';
export const UNSET_DISTRICT_PREFERENCE = 'UNSET_DISTRICT_PREFERENCE';

export const DESTROY_SESSION = 'DESTROY_SESSION';
